// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwhsyvjpiniwbmdjkanr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3aHN5dmpwaW5pd2JtZGprYW5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2MjkzNjMsImV4cCI6MjA4NjIwNTM2M30.wK3T6kxEJX424Q2TKD1wtwGRf_68UG-yRfroywIxby0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});